apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: master
spec:
  volumeMode: Filesystem
  storageClassName: slow-jenkins-volume 
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
