apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: master
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.60.3-alpine
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: volume1          
      volumes:
      - name: volume1
        persistentVolumeClaim:
          claimName: low-jenkins-volume  